[theme]
base = "dark"
primaryColor = "#36D2C9"
backgroundColor = "#0E1219"
secondaryBackgroundColor = "#151D2B"
textColor = "#F2F4F8"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
