$repoRoot = Split-Path -Path $PSScriptRoot -Parent
$snapshotPath = Join-Path $repoRoot "src\data\mlb\processed\snapshots\model_ready_features_mlb_HEAD.csv"

if (-not (Test-Path $snapshotPath)) {
    Write-Error "No existe snapshot baseline: $snapshotPath"
    exit 1
}

$env:NBA_MLB_INPUT_FILE = $snapshotPath
$env:NBA_MLB_MARKETS = "full_game"
$env:NBA_MLB_FULL_GAME_XGB_WEIGHT_GRID = "0.00,0.20,0.35,0.50,0.65,0.80,1.00"
$env:NBA_MLB_FULL_GAME_BRIER_WEIGHT = "0.08"
$env:NBA_MLB_FULL_GAME_PROB_SHIFT_ENABLED = "1"
$env:NBA_MLB_FULL_GAME_PROB_SHIFT_MIN = "-0.02"
$env:NBA_MLB_FULL_GAME_PROB_SHIFT_MAX = "0.02"
$env:NBA_MLB_FULL_GAME_PROB_SHIFT_STEP = "0.01"
$env:NBA_MLB_FULL_GAME_CALIBRATOR_MODE = "global_lr"
$env:NBA_MLB_FULL_GAME_THR_MIN = "0.54"
$env:NBA_MLB_FULL_GAME_THR_MAX = "0.66"
$env:NBA_MLB_FULL_GAME_THR_STEP = "0.01"
$env:NBA_MLB_FULL_GAME_THRESHOLD_OBJECTIVE = "roi"
$env:NBA_MLB_FULL_GAME_ROI_MIN_EDGE = "0.00"
$env:NBA_MLB_FULL_GAME_ROI_MIN_ACCURACY = "0.45"
$env:NBA_MLB_FULL_GAME_ROI_MIN_PRICED_ROWS = "8"
$env:NBA_MLB_FULL_GAME_VOL_NORM_ENABLED = "1"
$env:NBA_MLB_FULL_GAME_VOL_NORM_ALPHA = "0.18"
$env:NBA_MLB_FULL_GAME_VOL_NORM_THRESHOLD_BONUS = "0.02"
$env:NBA_MLB_FULL_GAME_VOL_NORM_HIGH_QUANTILE = "0.75"
$env:NBA_MLB_FULL_GAME_VOL_NORM_MIN_ROWS = "160"
$env:NBA_MLB_FULL_GAME_VOL_DECISION_ENABLED = "1"
$env:NBA_MLB_FULL_GAME_VOL_DECISION_BETA = "-0.08"
$env:NBA_MLB_FULL_GAME_VOL_DECISION_MAX_SHIFT = "0.04"
$env:NBA_MLB_FULL_GAME_VOL_DECISION_BETA_GRID = "-0.08"
$env:NBA_MLB_FULL_GAME_RELIABILITY_ENABLED = "0"
$env:NBA_MLB_FULL_GAME_RELIABILITY_SHRINK_ALPHA = "0.14"
$env:NBA_MLB_FULL_GAME_RELIABILITY_SIDE_SHIFT = "0.035"
$env:NBA_MLB_FULL_GAME_RELIABILITY_CONFLICT_SHIFT = "0.018"

Write-Host "MLB baseline global-accuracy environment loaded." -ForegroundColor Green
Write-Host "NBA_MLB_INPUT_FILE=$env:NBA_MLB_INPUT_FILE"
