@echo off
set "MODE_FILE=%~dp0mlb_profile_mode.txt"
set "MODE=baseline578"

if exist "%MODE_FILE%" (
  for /f "usebackq tokens=* delims=" %%A in ("%MODE_FILE%") do (
    if not "%%A"=="" set "MODE=%%A"
  )
)

set "MODE=%MODE: =%"
for %%I in ("%~dp0..") do set "ROOT=%%~fI"

if /I "%MODE%"=="live" (
  call "%~dp0mlb_clear_overrides.cmd"
  echo [MLB PROFILE] LIVE
  exit /b 0
)

if /I not "%MODE%"=="baseline578" (
  echo [MLB PROFILE] Modo desconocido "%MODE%". Usando baseline578.
  set "MODE=baseline578"
)

set "NBA_MLB_INPUT_FILE=%ROOT%\src\data\mlb\processed\snapshots\model_ready_features_mlb_HEAD.csv"
set "NBA_MLB_MAX_TRAIN_DATE="
set "NBA_MLB_FULL_GAME_XGB_WEIGHT_GRID=0.00,0.20,0.35,0.50,0.65,0.80,1.00"
set "NBA_MLB_FULL_GAME_BRIER_WEIGHT=0.08"
set "NBA_MLB_FULL_GAME_PROB_SHIFT_ENABLED=1"
set "NBA_MLB_FULL_GAME_PROB_SHIFT_MIN=-0.02"
set "NBA_MLB_FULL_GAME_PROB_SHIFT_MAX=0.02"
set "NBA_MLB_FULL_GAME_PROB_SHIFT_STEP=0.01"
set "NBA_MLB_FULL_GAME_CALIBRATOR_MODE=global_lr"
set "NBA_MLB_FULL_GAME_THR_MIN=0.54"
set "NBA_MLB_FULL_GAME_THR_MAX=0.66"
set "NBA_MLB_FULL_GAME_THR_STEP=0.01"
set "NBA_MLB_FULL_GAME_THRESHOLD_OBJECTIVE=roi"
set "NBA_MLB_FULL_GAME_ROI_MIN_EDGE=0.00"
set "NBA_MLB_FULL_GAME_ROI_MIN_ACCURACY=0.45"
set "NBA_MLB_FULL_GAME_ROI_MIN_PRICED_ROWS=8"
set "NBA_MLB_FULL_GAME_VOL_NORM_ENABLED=1"
set "NBA_MLB_FULL_GAME_VOL_NORM_ALPHA=0.18"
set "NBA_MLB_FULL_GAME_VOL_NORM_THRESHOLD_BONUS=0.02"
set "NBA_MLB_FULL_GAME_VOL_NORM_HIGH_QUANTILE=0.75"
set "NBA_MLB_FULL_GAME_VOL_NORM_MIN_ROWS=160"
set "NBA_MLB_FULL_GAME_VOL_DECISION_ENABLED=1"
set "NBA_MLB_FULL_GAME_VOL_DECISION_BETA=-0.08"
set "NBA_MLB_FULL_GAME_VOL_DECISION_MAX_SHIFT=0.04"
set "NBA_MLB_FULL_GAME_VOL_DECISION_BETA_GRID=-0.08"
set "NBA_MLB_FULL_GAME_RELIABILITY_ENABLED=0"
set "NBA_MLB_FULL_GAME_RELIABILITY_SHRINK_ALPHA=0.14"
set "NBA_MLB_FULL_GAME_RELIABILITY_SIDE_SHIFT=0.035"
set "NBA_MLB_FULL_GAME_RELIABILITY_CONFLICT_SHIFT=0.018"
set "NBA_MLB_FULL_GAME_DROP_FEATURES="

echo [MLB PROFILE] BASELINE578
exit /b 0
