$varsToClear = @(
    "NBA_MLB_INPUT_FILE",
    "NBA_MLB_MAX_TRAIN_DATE",
    "NBA_MLB_MARKETS",
    "NBA_MLB_FULL_GAME_XGB_WEIGHT_GRID",
    "NBA_MLB_FULL_GAME_BRIER_WEIGHT",
    "NBA_MLB_FULL_GAME_PROB_SHIFT_ENABLED",
    "NBA_MLB_FULL_GAME_PROB_SHIFT_MIN",
    "NBA_MLB_FULL_GAME_PROB_SHIFT_MAX",
    "NBA_MLB_FULL_GAME_PROB_SHIFT_STEP",
    "NBA_MLB_FULL_GAME_CALIBRATOR_MODE",
    "NBA_MLB_FULL_GAME_THR_MIN",
    "NBA_MLB_FULL_GAME_THR_MAX",
    "NBA_MLB_FULL_GAME_THR_STEP",
    "NBA_MLB_FULL_GAME_THRESHOLD_OBJECTIVE",
    "NBA_MLB_FULL_GAME_ROI_MIN_EDGE",
    "NBA_MLB_FULL_GAME_ROI_MIN_ACCURACY",
    "NBA_MLB_FULL_GAME_ROI_MIN_PRICED_ROWS",
    "NBA_MLB_FULL_GAME_VOL_NORM_ENABLED",
    "NBA_MLB_FULL_GAME_VOL_NORM_ALPHA",
    "NBA_MLB_FULL_GAME_VOL_NORM_THRESHOLD_BONUS",
    "NBA_MLB_FULL_GAME_VOL_NORM_HIGH_QUANTILE",
    "NBA_MLB_FULL_GAME_VOL_NORM_MIN_ROWS",
    "NBA_MLB_FULL_GAME_VOL_DECISION_ENABLED",
    "NBA_MLB_FULL_GAME_VOL_DECISION_BETA",
    "NBA_MLB_FULL_GAME_VOL_DECISION_MAX_SHIFT",
    "NBA_MLB_FULL_GAME_VOL_DECISION_BETA_GRID",
    "NBA_MLB_FULL_GAME_RELIABILITY_ENABLED",
    "NBA_MLB_FULL_GAME_RELIABILITY_SHRINK_ALPHA",
    "NBA_MLB_FULL_GAME_RELIABILITY_SIDE_SHIFT",
    "NBA_MLB_FULL_GAME_RELIABILITY_CONFLICT_SHIFT",
    "NBA_MLB_FULL_GAME_DROP_FEATURES"
)

foreach ($name in $varsToClear) {
    Remove-Item -Path "Env:$name" -ErrorAction SilentlyContinue
}

Write-Host "MLB overrides cleared for current shell." -ForegroundColor Yellow
